version: '3.9'

services:
  
  dbpostgres_lojaonline:
    image: postgres:15.4-alpine3.18
    container_name: dbpostgres_loja
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersenha
      POSTGRES_DB: db_loja
    volumes: 
      - ./tmp_data/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - user-bridge
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management-alpine
    # restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=supersenha
    networks:
      - user-bridge
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./tmp_data/rabbitmq_data:/var/lib/rabbitmq

networks:
  user-bridge:
    name: user-bridge